__title__ = "pick-and-place"
__description__ = "Robotic pick and place system using XArm robot and RealSense camera"
__version__ = "1.0.0"
__author__ = "Adam Gormley"
__copyright__ = "Copyright 2025, Pick and Place Developer"
__author_email__ = "adam.gormley@rutgers.edu"
